substitutions:
  name: "jxd-r6-e1eth-lcd-wifi"
  friendly_name: JXD-R6-E1ETH-LCD
  version: 1.0.0

packages:
  board: !include boards/jxd-cpu-e1eth.yaml
  relay_board: !include boards/jxd-d6-r6-rev1.2.yaml
  i2c: !include peripheral/i2c.yaml
  uarts: !include peripheral/uarts.yaml
  temperature: !include features/temperature.yaml
  rtc_time: !include features/rtc-time.yaml
  vin_measure: !include features/vin-measure.yaml
  modbus: !include features/modbus-server.yaml
  display_off: !include features/display-off.yaml
  display: !include display/display.yaml
  status_page: !include display/status-page.yaml
  time_page: !include display/time-page.yaml
  blank_page: !include display/blank-page.yaml
  menu: !include display/menu.yaml
  buttons: !include display/buttons.yaml
  wifi: !include features/wifi.yaml
  menu_items: !include display/menu-items-wifi.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  project:
    name: JetHub.JXD R6-E1ETH-LCD
    version: ${version}
  on_boot:
    - priority: 600
      then:
        - delay: 200ms
        - script.execute: setup_time

dashboard_import:
  package_import_url: github://jethome-iot/esphome-device-configs/jxd-r6-e1eth-lcd-wifi.yaml@refactor/simplify-configs
  import_full_config: true
