# The main page's link icon, and the C++ expression that picks its state.
substitutions:
  link_connected: id(ethernet_id).is_connected()

image:
  - file: res/ethernet.svg
    id: icon_link
    type: BINARY

  - file: res/ethernet-off.svg
    id: icon_link_off
    type: BINARY

ethernet:
  id: ethernet_id
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    mode: CLK_OUT
    pin: 17
  phy_addr: 1
  power_pin: GPIO15

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "Ethernet IP"
      address_0:
        id: ip
    mac_address:
      name: "Ethernet MAC"
      id: mac_eth
