# The main page's link icon, and the C++ expression that picks its state.
substitutions:
  link_connected: id(wifi_id).is_connected()

image:
  - platform: file
    file: res/wifi.svg
    id: icon_link
    type: BINARY

  - platform: file
    file: res/wifi-off.svg
    id: icon_link_off
    type: BINARY

wifi:
  id: wifi_id
  reboot_timeout: 5min
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password

captive_portal:
  id: captive_portal_id

script:
  - id: reset_wifi
    then:
      - logger.log: 'Reset WiFi creds'
      - lambda: |-
          id(wifi_id).save_wifi_sta("", "");
          App.safe_reboot();

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WiFi IP"
      web_server:
        sorting_group_id: group_network
        sorting_weight: 1
      id: ip
    mac_address:
      name: "WiFi MAC"
      web_server:
        sorting_group_id: group_network
        sorting_weight: 2
      id: mac_wifi
