#!/usr/bin/env python3
"""Generate the self-contained device configs that dashboard_import serves.

``dashboard_import`` with ``import_full_config: true`` hands the ESPHome Builder
a single YAML file fetched from raw.githubusercontent, and nothing else. A
config assembled the way this repository maintains them cannot survive that trip
twice over: the ``packages:``/``!include`` tree has no sibling files to resolve
against on the importing machine, and ``font: file:`` paths are looked up
against the *importing user's* config directory rather than the file that
declared them, so a checked-out ``fonts/`` is invisible too.

So the tree that is pleasant to maintain and the file that is importable are two
different artifacts. This script derives the second from the first:

* Packages are merged in, but substitutions are deliberately *not* applied.
  ESPHome's own pass order is packages -> substitutions -> merge; skipping the
  middle pass leaves ``${name}`` and ``${friendly_name}`` symbolic, which is
  what the Builder rewrites when it renames an adopted device. Resolving them
  here would freeze the factory name into the display lambda forever.
* Every ``file:`` value that resolves to a file in this repository is rewritten
  to a raw.githubusercontent URL. The font component downloads and caches those
  like any other web font.

The repository, ref and output path all come from the source config's own
``package_import_url``, so that URL is the single place the branch is named.

Usage:
    scripts/build-dist.py            # regenerate dist/
    scripts/build-dist.py --check    # fail if dist/ is stale (for CI)
"""

from __future__ import annotations

import argparse
import io
from pathlib import Path
import sys
import tempfile
from typing import Any

from esphome import yaml_util
from esphome.components.packages import do_packages_pass, merge_packages
from esphome.core import CORE
from esphome.git import GitFile
from ruamel.yaml import YAML

REPO_ROOT = Path(__file__).resolve().parent.parent

HEADER = """\
# Generated by scripts/build-dist.py — do not edit.
#
# Self-contained build of {source}, served to the ESPHome Builder by
# dashboard_import. Edit the source config and its packages, then regenerate.
"""


def device_configs() -> list[Path]:
    """Root-level YAML files, skipping dotfiles and the local secrets store."""
    return sorted(
        path
        for path in REPO_ROOT.glob("*.yaml")
        if not path.name.startswith(".") and path.name != "secrets.yaml"
    )


def flatten(path: Path) -> dict[str, Any]:
    """Merge the config's packages without applying substitutions."""
    CORE.reset()
    CORE.config_path = path
    config = yaml_util.load_yaml(path)
    config = do_packages_pass(config, command_line_substitutions=None)
    return merge_packages(config)


def rewrite_local_assets(node: Any, raw_base: str, rewritten: list[str]) -> None:
    """Point every ``file:`` that names a repository file at its raw URL.

    Values that are not repository files — ``gfonts://`` shorthand, URLs that
    are already absolute — do not match and are left alone.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "file" and isinstance(value, str):
                if (REPO_ROOT / value).is_file():
                    node[key] = f"{raw_base}/{value}"
                    rewritten.append(value)
                    continue
            rewrite_local_assets(value, raw_base, rewritten)
    elif isinstance(node, list):
        for item in node:
            rewrite_local_assets(item, raw_base, rewritten)


def _typed(node: Any) -> Any:
    """Strip ESPHome's scalar wrappers, keeping the distinction that matters.

    ``bool`` is checked before ``int`` because it is a subclass of it, and the
    type tag is kept so a value that turns from the string ``"Yes"`` into the
    boolean ``True`` compares unequal.
    """
    if isinstance(node, dict):
        return {str(key): _typed(value) for key, value in node.items()}
    if isinstance(node, list):
        return [_typed(value) for value in node]
    if isinstance(node, bool):
        return ("bool", node)
    if isinstance(node, int):
        return ("int", int(node))
    if isinstance(node, float):
        return ("float", float(node))
    if node is None:
        return ("none", None)
    return ("str", str(node))


def _diff(left: Any, right: Any, path: str = "") -> list[str]:
    """Paths where two ``_typed`` trees disagree."""
    if isinstance(left, dict) and isinstance(right, dict):
        return [
            problem
            for key in left.keys() | right.keys()
            for problem in _diff(left.get(key), right.get(key), f"{path}/{key}")
        ]
    if isinstance(left, list) and isinstance(right, list) and len(left) == len(right):
        return [
            problem
            for index, (a, b) in enumerate(zip(left, right))
            for problem in _diff(a, b, f"{path}[{index}]")
        ]
    if left != right:
        return [f"{path}: {left!r} -> {right!r}"]
    return []


def _load_text(text: str) -> Any:
    """Parse with ESPHome's own loader, which is what actually reads the file."""
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "config.yaml"
        path.write_text(text)
        return yaml_util.load_yaml(path)


def verify_import_roundtrip(source: Path, text: str) -> None:
    """Fail if the ESPHome Builder would corrupt this file while importing it.

    When the config sets ``name_add_mac_suffix``, ``dashboard_import`` rewrites
    the device name by round-tripping the downloaded YAML through ruamel, which
    parses as YAML 1.2 and drops quotes that are only meaningful in YAML 1.1.
    A quoted ``'Yes'`` comes back as a bare ``Yes``, which ESPHome's own YAML 1.1
    loader then reads as the boolean ``true``. Values like these have to be
    spelled so that they survive the trip; catching it here beats shipping a
    config that only breaks once somebody imports it.
    """
    ruamel = YAML()
    buffer = io.StringIO()
    ruamel.dump(ruamel.load(text), buffer)

    problems = _diff(_typed(_load_text(text)), _typed(_load_text(buffer.getvalue())))
    if problems:
        listed = "\n".join(f"    {problem}" for problem in sorted(problems))
        raise SystemExit(
            f"{source.name}: these values would be corrupted by dashboard_import's "
            f"ruamel round-trip:\n{listed}\n"
            f"  Spell them so YAML 1.1 and 1.2 agree — 'true' as '1', 'Yes' as a "
            f"word that is not a boolean."
        )


def render(source: Path) -> tuple[Path, str] | None:
    """Return the dist path and contents for one device config, or None."""
    config = flatten(source)

    dashboard_import = config.get("dashboard_import")
    if not dashboard_import:
        return None

    import_url = dashboard_import["package_import_url"]
    git_file = GitFile.from_shorthand(import_url)
    if not git_file.ref:
        raise SystemExit(
            f"{source.name}: package_import_url must pin a ref, got {import_url!r}"
        )

    # raw_url ends with the filename; everything before it is the raw base that
    # sibling assets hang off. Derived rather than formatted so a non-GitHub
    # forge keeps working if package_import_url ever moves.
    raw_url = git_file.raw_url
    if not raw_url.endswith(git_file.filename):
        raise SystemExit(f"{source.name}: cannot derive a raw base from {raw_url!r}")
    raw_base = raw_url[: -len(git_file.filename)].rstrip("/")

    target = REPO_ROOT / git_file.filename
    if target == source:
        raise SystemExit(
            f"{source.name}: package_import_url still points at the source config. "
            f"Point it at the generated file, e.g. dist/{source.name}."
        )

    rewritten: list[str] = []
    rewrite_local_assets(config, raw_base, rewritten)
    print(f"  {source.name}: {len(rewritten)} asset(s) -> {raw_base}")

    body = yaml_util.dump(config)
    verify_import_roundtrip(source, body)
    return target, HEADER.format(source=source.name) + "\n" + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated files are up to date instead of writing them",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for source in device_configs():
        rendered = render(source)
        if rendered is None:
            continue
        target, contents = rendered

        if args.check:
            current = target.read_text() if target.is_file() else None
            if current != contents:
                stale.append(target)
            continue

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(contents)
        print(f"  wrote {target.relative_to(REPO_ROOT)}")

    if stale:
        names = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
        print(f"\nout of date: {names}\nRun scripts/build-dist.py and commit the result.")
        return 1
    if args.check:
        print("\ndist/ is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
