#!/usr/bin/env python3
"""Build the main page's status icons, into res/.

Each icon is a 16x16 pixel map here and a run of filled rects in the SVG. Strokes
and arcs would be simpler to write, but cairosvg antialiases them and ESPHome's
BINARY image type then thresholds at 50%, which breaks thin diagonals apart.

Usage:
    scripts/build-icons.py            # regenerate res/
    scripts/build-icons.py --check    # fail if res/ is stale
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "res"
SIZE = 16

# The "-off" variant of each icon, drawn by strike(): a 2px diagonal with a 1px
# gap cleared around it, so the slash stays legible over the art it crosses.
STRIKE_WIDTH = 2
STRIKE_GAP = 1

HEADER = "Generated by scripts/build-icons.py - do not edit."

ICONS = {
    # RJ45 plug: five contacts inside the body, cable tail below it.
    "ethernet": """
        ................
        .#############..
        .#.#.#.#.#.#.#..
        .#.#.#.#.#.#.#..
        .#.#.#.#.#.#.#..
        .#...........#..
        .#...........#..
        .#...........#..
        .#...........#..
        .#...........#..
        .#############..
        ......###.......
        ......###.......
        ......###.......
        ......###.......
        ................
    """,
    # Arcs of one family: centre (8, 14.5), radii 11/8/5 and the square where
    # radius 2 falls, so the apexes sit three rows apart. Bands are 1px because a
    # width between 1 and 2 straddles pixel rows and rasterises ragged.
    "wifi": """
        ................
        ................
        ................
        ....########....
        ..###......###..
        ..#..........#..
        .....######.....
        ....##....##....
        ................
        ......####......
        ................
        ................
        .......##.......
        .......##.......
        ................
        ................
    """,
    # Home Assistant: house outline around the three-node mark.
    "ha": """
        ................
        .......##.......
        ......#..#......
        .....#....#.....
        ....#......#....
        ...#........#...
        ..#..........#..
        .#.....##.....#.
        .#.....##.....#.
        .#............#.
        .#..##....##..#.
        .#..##....##..#.
        .#............#.
        .#............#.
        .##############.
        ................
    """,
}

Grid = list[list[bool]]


def parse(art: str) -> Grid:
    rows = [line.strip() for line in art.strip().splitlines()]
    if len(rows) != SIZE or any(len(row) != SIZE for row in rows):
        raise SystemExit(f"icon map must be {SIZE}x{SIZE}, got {len(rows)} rows")
    return [[char == "#" for char in row] for row in rows]


def strike(grid: Grid) -> Grid:
    """The icon crossed out: clear the diagonal's neighbourhood, then draw it."""
    out = [row[:] for row in grid]
    for y in range(SIZE):
        for x in range(SIZE):
            if -STRIKE_GAP <= x - y < STRIKE_WIDTH + STRIKE_GAP:
                out[y][x] = False
    for y in range(1, SIZE - 1):
        for x in range(y, min(y + STRIKE_WIDTH, SIZE)):
            out[y][x] = True
    return out


def runs(grid: Grid):
    """Horizontal runs of set pixels, as (x, y, width)."""
    for y, row in enumerate(grid):
        x = 0
        while x < SIZE:
            if not row[x]:
                x += 1
                continue
            start = x
            while x < SIZE and row[x]:
                x += 1
            yield start, y, x - start


def to_svg(grid: Grid) -> str:
    art = "\n".join(
        "     " + "".join("#" if pixel else "." for pixel in row) for row in grid
    )
    rects = "\n".join(
        f'  <rect x="{x}" y="{y}" width="{width}" height="1"/>'
        for x, y, width in runs(grid)
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{SIZE}" height="{SIZE}" '
        f'viewBox="0 0 {SIZE} {SIZE}" fill="black">\n'
        f"  <!-- {HEADER}\n{art}\n  -->\n{rects}\n</svg>\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated files are up to date instead of writing them",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    OUT_DIR.mkdir(exist_ok=True)
    for name, art in ICONS.items():
        grid = parse(art)
        for target, contents in (
            (OUT_DIR / f"{name}.svg", to_svg(grid)),
            (OUT_DIR / f"{name}-off.svg", to_svg(strike(grid))),
        ):
            if args.check:
                if (target.read_text() if target.is_file() else None) != contents:
                    stale.append(target)
                continue
            target.write_text(contents)
            print(f"  wrote {target.relative_to(REPO_ROOT)}")

    if stale:
        names = ", ".join(str(path.relative_to(REPO_ROOT)) for path in stale)
        print(
            f"\nout of date: {names}\nRun scripts/build-icons.py and commit the result."
        )
        return 1
    if args.check:
        print("\nres/ is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
