#!/usr/bin/env python3
"""Build the self-contained configs that dashboard_import serves, into dist/.

Merges each device config's packages and rewrites local asset paths to raw URLs,
so the single file the ESPHome Builder downloads stands on its own.

Usage:
    scripts/build-dist.py            # regenerate dist/
    scripts/build-dist.py --check    # fail if dist/ is stale
"""

from __future__ import annotations

import argparse
from functools import cache
import io
from pathlib import Path
import sys
import tempfile
from typing import Any

from esphome import yaml_util
from esphome.components.packages import do_packages_pass, merge_packages
from esphome.core import CORE
from esphome.git import GitFile
from ruamel.yaml import YAML
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

# Keys whose value names an asset file. Anything else pointing at a repository
# file is caught by find_local_paths() rather than silently shipped.
ASSET_KEYS = {"file"}

HEADER = "# Generated by scripts/build-dist.py from {source} — do not edit.\n"


def device_configs() -> list[Path]:
    return sorted(
        path
        for path in REPO_ROOT.glob("*.yaml")
        if not path.name.startswith(".") and path.name != "secrets.yaml"
    )


def flatten(path: Path) -> dict[str, Any]:
    """Merge packages, skipping the substitution pass.

    ESPHome's order is packages -> substitutions -> merge. Leaving out the middle
    pass keeps ${name} and ${friendly_name} symbolic, which is what the Builder
    rewrites when it renames an adopted device.
    """
    CORE.reset()
    CORE.config_path = path
    try:
        config = yaml_util.load_yaml(path)
        config = do_packages_pass(config, command_line_substitutions=None)
    except Exception as err:
        # The WiFi config reads !secret, and a traceback buries that.
        if not (REPO_ROOT / "secrets.yaml").is_file():
            raise SystemExit(
                f"{path.name}: {err}\n"
                "  No secrets.yaml: copy secrets.yaml.example to secrets.yaml."
            ) from err
        raise
    return merge_packages(config)


def _repo_file(value: Any) -> str | None:
    """The value as a repository-relative path, if it names a file in the repo."""
    if not isinstance(value, str) or not value or "://" in value:
        return None
    if value.startswith("/") or "\n" in value:
        return None
    try:
        return value if (REPO_ROOT / value).is_file() else None
    except OSError:
        return None


def rewrite_assets(node: Any, raw_base: str, rewritten: list[str]) -> None:
    if isinstance(node, dict):
        for key, value in node.items():
            if key in ASSET_KEYS and (path := _repo_file(value)):
                node[key] = f"{raw_base}/{path}"
                rewritten.append(path)
            else:
                rewrite_assets(value, raw_base, rewritten)
    elif isinstance(node, list):
        for item in node:
            rewrite_assets(item, raw_base, rewritten)


class BlockStr(str):
    """String emitted as a literal block scalar, which no YAML version resolves."""


@cache
def needs_block_style(value: str) -> bool:
    """Whether a YAML 1.2 round-trip would leave this bare for 1.1 to misread.

    dashboard_import re-emits the file with ruamel, which quotes only what YAML 1.2
    would resolve; ESPHome then reads the result as YAML 1.1, which resolves more —
    `Yes` as a boolean, `12:30` as 750.
    """
    try:
        buffer = io.StringIO()
        YAML().dump({"v": value}, buffer)
        return not isinstance(yaml.safe_load(buffer.getvalue())["v"], str)
    except Exception:
        return False


def _represent_block(dumper: Any, value: BlockStr) -> Any:
    return dumper.represent_scalar("tag:yaml.org,2002:str", str(value), style="|")


# Exact-type representers win over the multi-representer ESPHome registers for str.
yaml_util.ESPHomeDumper.add_representer(BlockStr, _represent_block)


def harden_scalars(node: Any) -> Any:
    """Wrap values a YAML 1.2 round-trip would hand back as non-strings."""
    if isinstance(node, dict):
        return {key: harden_scalars(value) for key, value in node.items()}
    if isinstance(node, list):
        return [harden_scalars(value) for value in node]
    if isinstance(node, str) and not isinstance(node, BlockStr):
        if needs_block_style(str(node)):
            return BlockStr(node)
    return node


def find_local_paths(node: Any, path: str = "") -> list[str]:
    """Values still naming a repository file, which the importer cannot resolve."""
    if isinstance(node, dict):
        return [
            found
            for key, value in node.items()
            for found in find_local_paths(value, f"{path}/{key}")
        ]
    if isinstance(node, list):
        return [
            found
            for index, value in enumerate(node)
            for found in find_local_paths(value, f"{path}[{index}]")
        ]
    return [f"{path}: {node}"] if _repo_file(node) else []


def _typed(node: Any) -> Any:
    """Drop ESPHome's scalar wrappers, keeping the type so "Yes" != True."""
    if isinstance(node, dict):
        return {str(key): _typed(value) for key, value in node.items()}
    if isinstance(node, list):
        return [_typed(value) for value in node]
    if isinstance(node, bool):
        return ("bool", node)
    if isinstance(node, int):
        return ("int", int(node))
    if isinstance(node, float):
        return ("float", float(node))
    if node is None:
        return ("none", None)
    return ("str", str(node))


def _diff(left: Any, right: Any, path: str = "") -> list[str]:
    if isinstance(left, dict) and isinstance(right, dict):
        return [
            problem
            for key in left.keys() | right.keys()
            for problem in _diff(left.get(key), right.get(key), f"{path}/{key}")
        ]
    if isinstance(left, list) and isinstance(right, list) and len(left) == len(right):
        return [
            problem
            for index, (a, b) in enumerate(zip(left, right))
            for problem in _diff(a, b, f"{path}[{index}]")
        ]
    return [] if left == right else [f"{path}: {left!r} -> {right!r}"]


def _load_text(text: str) -> Any:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "config.yaml"
        path.write_text(text)
        return yaml_util.load_yaml(path)


def verify_import_roundtrip(source: Path, text: str) -> None:
    """Fail on values the Builder would corrupt while renaming the device.

    dashboard_import round-trips the file through ruamel, which reads YAML 1.2 and
    drops quotes that only matter in 1.1: a quoted 'Yes' comes back bare, and
    ESPHome's own loader then reads it as the boolean true.
    """
    ruamel = YAML()
    buffer = io.StringIO()
    ruamel.dump(ruamel.load(text), buffer)

    problems = _diff(_typed(_load_text(text)), _typed(_load_text(buffer.getvalue())))
    if problems:
        listed = "\n".join(f"    {problem}" for problem in sorted(problems))
        raise SystemExit(
            f"{source.name}: dashboard_import would corrupt these values, and "
            f"harden_scalars() could not save them:\n{listed}"
        )


def render(source: Path) -> tuple[Path, str] | None:
    config = flatten(source)

    dashboard_import = config.get("dashboard_import")
    if not dashboard_import:
        return None

    import_url = dashboard_import["package_import_url"]
    git_file = GitFile.from_shorthand(import_url)
    if not git_file.ref:
        raise SystemExit(
            f"{source.name}: package_import_url must pin a ref, got {import_url!r}"
        )

    raw_url = git_file.raw_url
    if not raw_url.endswith(git_file.filename):
        raise SystemExit(f"{source.name}: cannot derive a raw base from {raw_url!r}")
    raw_base = raw_url[: -len(git_file.filename)].rstrip("/")

    target = REPO_ROOT / git_file.filename
    if target == source:
        raise SystemExit(
            f"{source.name}: package_import_url still points at the source config. "
            f"Point it at the generated file, e.g. dist/{source.name}."
        )

    rewritten: list[str] = []
    rewrite_assets(config, raw_base, rewritten)

    if leftover := find_local_paths(config):
        listed = "\n".join(f"    {item}" for item in sorted(leftover))
        raise SystemExit(
            f"{source.name}: these still point at repository files, which an "
            f"importing user does not have:\n{listed}\n"
            f"  Add the key to ASSET_KEYS if it names an asset, or inline the value."
        )

    print(f"  {source.name}: {len(rewritten)} asset(s) -> {raw_base}")

    body = yaml_util.dump(harden_scalars(config))
    verify_import_roundtrip(source, body)
    return target, HEADER.format(source=source.name) + "\n" + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated files are up to date instead of writing them",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for source in device_configs():
        rendered = render(source)
        if rendered is None:
            continue
        target, contents = rendered

        if args.check:
            if (target.read_text() if target.is_file() else None) != contents:
                stale.append(target)
            continue

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(contents)
        print(f"  wrote {target.relative_to(REPO_ROOT)}")

    if stale:
        names = ", ".join(str(path.relative_to(REPO_ROOT)) for path in stale)
        print(
            f"\nout of date: {names}\nRun scripts/build-dist.py and commit the result."
        )
        return 1
    if args.check:
        print("\ndist/ is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
